'use strict';
const $=id=>document.getElementById(id);let token='',mode='calm',history=[],voices=[],busy=false,controller=null;
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-AIRI-Token':token},body:body?JSON.stringify(body):undefined,signal:body?controller?.signal:undefined});const v=await r.json();if(!r.ok)throw Error(v.error||'Request failed');return v;}
function currentMode(){return $('guest').checked?'calm':mode;}
function setMode(next){if(busy)controller?.abort();mode=next;window.speechSynthesis?.cancel();for(const b of document.querySelectorAll('[data-mode]'))b.setAttribute('aria-pressed',String(b.dataset.mode===mode));$('mode-status').textContent=$('guest').checked?'손님 모드 · 부드러운 말투':({calm:'Calm · 욕설 없는 기본 말투',playful:'Playful · 가벼운 장난',unhinged:'Unhinged · 욕설이 포함될 수 있습니다'})[mode];}
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{if(b.dataset.mode==='unhinged')$('guest').checked=false;setMode(b.dataset.mode);};$('guest').onchange=()=>setMode(mode);
function loadVoices(){const selected=$('voice').value;voices=window.speechSynthesis?.getVoices().filter(v=>v.localService)||[];$('voice').replaceChildren();for(const v of voices){const o=document.createElement('option');o.value=v.voiceURI;o.textContent=v.name+' · '+v.lang;$('voice').append(o);}if(voices.some(v=>v.voiceURI===selected))$('voice').value=selected;else if(voices.some(v=>v.lang.startsWith('ko')))$('voice').value=voices.find(v=>v.lang.startsWith('ko')).voiceURI;$('voice-status').textContent=voices.length?'이 기기에 설치된 음성만 사용합니다.':'로컬 음성이 없습니다. OS 음성 설정에서 목소리를 설치하세요. 대화는 텍스트로 사용할 수 있습니다.';$('preview').disabled=!voices.length;}
function speak(text){const voice=voices.find(v=>v.voiceURI===$('voice').value);if(!voice){$('voice-status').textContent='로컬 음성을 먼저 설치·선택하세요.';return;}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.voice=voice;utterance.lang=voice.lang;utterance.rate=Number($('rate').value);utterance.onstart=()=>{$('voice-status').textContent='읽는 중…';};utterance.onend=()=>{$('voice-status').textContent='재생 완료';};utterance.onerror=()=>{$('voice-status').textContent='음성을 재생하지 못했습니다. 다시 눌러 주세요.';};speechSynthesis.speak(utterance);}
$('preview').onclick=()=>speak({calm:'좋아. 오늘 할 일을 하나씩 정리해 보자.',playful:'오늘의 혼돈, 접수 완료. 하나씩 해치워 보자.',unhinged:'오늘도 할 일이 존나 많네. 좋아, 하나씩 끝내자.'}[currentMode()]);$('stop').onclick=()=>{window.speechSynthesis?.cancel();$('voice-status').textContent='음성을 중지했습니다.';};
if(window.speechSynthesis){speechSynthesis.addEventListener('voiceschanged',loadVoices);loadVoices();}else $('voice-status').textContent='이 브라우저는 음성 출력을 지원하지 않습니다. 텍스트 대화를 사용할 수 있습니다.';
function bubble(role,text,answerMode='calm'){$('messages').querySelector('.intro')?.remove();const div=document.createElement('div');div.className='bubble '+role;div.textContent=text;if(role==='assistant'){const b=document.createElement('button');b.textContent='다시 읽기';b.onclick=()=>{if(answerMode==='unhinged'&&currentMode()!=='unhinged'){$('voice-status').textContent='이 답변은 Unhinged 모드에서만 재생할 수 있습니다.';return;}speak(text);};div.append(b);}$('messages').append(div);$('messages').scrollTop=$('messages').scrollHeight;}
async function refresh(){try{const s=await api('status');const previous=$('model').value;$('model').replaceChildren();for(const name of s.models){const o=document.createElement('option');o.value=name;o.textContent=name;$('model').append(o);}if(s.models.includes(previous))$('model').value=previous;else{const preferred=['qwen3:4b','qwen3.5:9b','exaone3.5:7.8b','llama3.1:latest'].find(name=>s.models.includes(name));if(preferred)$('model').value=preferred;}$('connection').textContent=s.connected?(s.models.length?'로컬 Ollama 연결됨':'Ollama에 로컬 대화 모델을 설치하세요.'):s.error;$('send').disabled=!s.models.length||busy;}catch(e){$('connection').textContent=e.message;}}
$('refresh').onclick=refresh;$('clear').onclick=()=>{controller?.abort();window.speechSynthesis?.cancel();history=[];$('messages').replaceChildren();$('status').textContent='새 대화입니다. 이전 기록을 비웠습니다.';};
$('chat-form').onsubmit=async e=>{e.preventDefault();const text=$('message').value.trim();if(busy||!text)return;busy=true;controller=new AbortController();$('send').disabled=true;bubble('user',text);$('message').value='';$('status').textContent='로컬 모델이 답변을 만들고 있어요…';const sentMode=currentMode();try{const result=await api('chat',{text,model:$('model').value,mode,guest:$('guest').checked,history:history.slice(-12)});history.push({role:'user',content:text},{role:'assistant',content:result.text});history=history.slice(-12);bubble('assistant',result.text,result.mode);$('status').textContent=result.model+' · '+result.mode;if($('auto-speak').checked&&currentMode()===sentMode)speak(result.text);}catch(error){$('status').textContent=error.name==='AbortError'?'대화를 중지했습니다.':error.message;}finally{busy=false;controller=null;$('send').disabled=!$('model').value;}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)window.speechSynthesis?.cancel();});
(async()=>{try{token=(await api('bootstrap')).token;await refresh();}catch(e){$('status').textContent=e.message;}})();
